---
- name: Create /var/repo directory
  file:
    path: /var/repo
    state: directory
    owner: phd
    mode: 0775

- name: Set diffusion user
  command: ./bin/config set diffusion.ssh-user git
  args:
    chdir: /home/phd/phabricator