---
- name: Install Packages
  apt:
    name:
    - imagemagick
    state: present

- name: Enable Imagemagick in Phabricator configuration
  command: ./bin/config set files.enable-imagemagick true
  args:
    chdir: /home/phd/phabricator