---
# Ansible playbook for a Phabricator setup.
#
# @author Nicholas Luo (2017).

- hosts: phabricator
  gather_facts: yes

  vars_files:
    - vars/main.yml

  roles:
    - geerlingguy.nginx
    - geerlingguy.mysql
    - geerlingguy.php-versions
    - geerlingguy.php
    - geerlingguy.php-mysql
    - phabricator
